version: "3.2"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbit_data:/var/lib/rabbitmq/
        - rabbit_logs:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASSWORD}

  client_mobile:
    build: "./mobile"
    depends_on:
      - client_web
    volumes:
      - client_data:/app

  client_web:
    build: "./web"
    # depends_on:
    #   - server
    ports:
      - ${CLIENT_PORT}:80
    volumes:
      - client_data:/usr/share/nginx/html

  # server:
  #   ports:
  #     - ${SERVER_PORT}:8080
  #   depends_on:
  #     - rabbitmq

volumes:
  rabbit_data:
  rabbit_logs:
  client_data: