name: Web-lint

on:
  push:
    paths: ["web/**"]
    branches: ["master", "dev"]
  pull_request:
    paths: ["web/**"]
    branches: ["master", "dev"]

defaults:
  run:
    working-directory: web

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dev dependencies
        run: yarn install
      - name: Run lint check
        run: yarn lint:check

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dev dependencies
        run: yarn install
      - name: Run cypress
        run: yarn cypress:run