name: Web-lint

on: [push, pull_request]

defaults:
  run:
    working-directory: web

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dev dependencies
        run: yarn install
      - name: Run lint check
        run: yarn lint:check